### ISSUE TITLE
mysql5.7 binlog_format = mixed  has some bug i think

### ISSUE THREAD

**Issue by domyway** [krowinski/php-mysql-replication#10]
mysql5.7 binlog_format = mixed :  

when I execute "UPDATE `hj_access` SET `access_type` = '/appver1' WHERE `hj_access`.`id` = 1"

dump_event.php output :  
"UPDATE `hj_access` SET `access_type` = '/appver1' WHERE `hj_access`.`id` = 1�0�w"

I think the length pass to BinaryDataReader->read() has something wrong.
but binlog_format = row  seems to be right.

**Comment by krowinski** [comment]
Hi
Currently only binlog-format  = row is supported 
https://github.com/krowinski/php-mysql-replication#mysql-server-settings

**Comment by domyway** [comment]
get it , thanks a lot .
