### ISSUE TITLE
Too many methods are private, very hard to extend

### ISSUE THREAD

**Issue by fimbulvetr** [krowinski/php-mysql-replication#13]
Greetings,

I've found too many of the properties and methods are private for me to usefully use or extend your library. When I want to make a quick change (i.e. backport ConstFieldType::DATETIME) into 1.x, I find that it takes an immense amount of work with respect to copy and pasting code just so i have access to the rowevent object that originally extended yours but slightly more logic in it.

Also, I do not want to use reflection but even if I did maintaining it is not tenable due to the sheer number of private properties. 

I would argue the purpose of a library is to allow some modification but I cannot find that spirit in this library and the hopes I have for the future require me to hook into things such as getColumnData or tablemap, etc. It's a shame because this is really nice code but it's still not worth effort. 

Even the config builder is too much of a burden to extend as the user that has permissions to repl data does not have access to information_schema.columns and I'd like to have it use two different connections for that but extending that requires extending all config/config* files, as well as repositories and factory file and the kicker is I need to copy and paste ALL of the code from those files because their properties are private!

Also the requirement of symfony 3.1 is tough, many libraries require 2 series and prevents an upgrade to your php-mysql-replication 2.x because of this. I understand some libraries need to lead the charge into newer symfonys, but this also prevents adoption.

**Comment by krowinski** [comment]
> Greetings,
Hi
> 
> I've found too many of the properties and methods are private for me to usefully use or extend your library. When I want to make a quick change (i.e. backport ConstFieldType::DATETIME) into 1.x, I find that it takes an immense amount of work with respect to copy and pasting code just so i have access to the rowevent object that originally extended yours but slightly more logic in it.
> 
If you need to backport feel free to add  code to this to this repo.

> Also, I do not want to use reflection but even if I did maintaining it is not tenable due to the sheer number of private properties.
> 
> I would argue the purpose of a library is to allow some modification but I cannot find that spirit in this library and the hopes I have for the future require me to hook into things such as getColumnData or tablemap, etc. It's a shame because this is really nice code but it's still not worth effort.

Again if getColumnData is missing something you need  or you want to extend create merge request.

> 
> Even the config builder is too much of a burden to extend as the user that has permissions to repl data does not have access to information_schema.columns and I'd like to have it use two different connections for that but extending that requires extending all config/config* files, as well as repositories and factory file and the kicker is I need to copy and paste ALL of the code from those files because their properties are private!

Extend MySQLReplicationFactory or create new, then change __construct 
```
        $this->connection = DriverManager::getConnection([
            'user' => $config->getUser(),
            'password' => $config->getPassword(),
            'host' => $config->getHost(),
            'port' => $config->getPort(),
            'driver' => 'pdo_mysql',
			'charset' => $config->getCharset()
        ]);
```
Replace with other user you need to.

Also you can extend MySQLRepository (all methods are public) and overwrite what you need.  

> 
> Also the requirement of symfony 3.1 is tough, many libraries require 2 series and prevents an upgrade to your php-mysql-replication 2.x because of this. I understand some libraries need to lead the charge into newer symfonys, but this also prevents adoption.

Sure, in next release it will be downgraded to 2.8 ( ">=2.8 <=3.1")
