### ISSUE TITLE
mysql 5.7x

### ISSUE THREAD

**Issue by java168** [krowinski/php-mysql-replication#23]
Hi, i am running mysql 5.7.x the call $this->binaryDataReader->readIntBeBySize(5) in getDatetime2 return a negative. (datetime column)
PHP Fatal error:  Uncaught exception 'Exception' with message 'DateTime::__construct(): Failed to parse time string (10069-12-11 12:60:15) at position 12 (1): Double time specification' in C:\php-mysql-replication\src\MySQLReplication\Event\RowEvent\RowEvent.php:646
Stack trace:
#0 C:\php-mysql-replication\src\MySQLReplication\Event\RowEvent\RowEvent.php(646): DateTime->__construct('10069-12-11 12:...')
#1 C:\php-mysql-replication\src\MySQLReplication\Event\RowEvent\RowEvent.php(402): MySQLReplication\Event\RowEvent\RowEvent->getDatetime2(Array)
#2 C:\php-mysql-replication\src\MySQLReplication\Event\RowEvent\RowEvent.php(898): MySQLReplication\Event\RowEvent\RowEvent->getColumnData('\xFF')
#3 C:\php-mysql-replication\src\MySQLReplication\Event\Event.php(118): MySQLReplication\Event\RowEvent\RowEvent->makeUpdateRowsDTO()
#4 C:\php-mysql-replication\src\MySQLReplication\MySQLReplicationFactory.php(142): MySQLReplication\Event\Event->consume()
#5 C:\php-mysql-replication\example\dump_events.php(57): MySQLReplication\MySQLReplicat in C:\php-mysql-replication\src\MySQLReplication\Event\RowEvent\RowEvent.php on line 646

i was able to run https://github.com/noplay/python-mysql-replication
does it support MySQL 5.7.x ? thank you very much

**Comment by krowinski** [comment]
Hi, it should be working. I will test this later. Are you able to check how update query looked like  for datetime column and write here ?

**Comment by java168** [comment]
Hi krowinski,
thank you very much for looking into it.
PHP: C:\Program Files (x86)\iis express\PHP\v5.6\php.exe
MySQL 5.7.17 
binlog-format    = row 
======================
test 1:
table : mytest
aa: int(11)
bb: varchar(10)
cc: timestamp
UPDATE mytest SET cc = NOW() WHERE aa = 1

no error
===============================
test2:
table : mytest
aa: int(11)
bb: varchar(10)
cc: timestamp
dd: datetime
UPDATE mytest SET cc = NOW(), dd=NOW()  WHERE aa = 1
failed with the same error i got Yesterday in datetime column.
the date part is wrong but the time part is correct. really strange

**Comment by java168** [comment]
thank you very much. 
i installed the tool in my ubuntu 16.04 (MySQL 5.7.18 and PHP 5.6.30)
everything works. 
very likely it is mysql or php on the windows platform.
thank you for your helps 👍

**Comment by java168** [comment]
i just figured it out. if you are running it on windows platform then save your time and go get the PHP 7 64 bits version. the old version would return negative number in datetime field.
this command : php -r "var_dump((int) 659761444178);" will return 659761444178.
THANK YOU VERY MUCH krowinski for your great tool.   i can run it on windows platform :)
