### ISSUE TITLE
Unable to start reading from a past point by using withBinLogPosition

### ISSUE THREAD

**Issue by pushkarprasad007** [krowinski/php-mysql-replication#26]
I've also added a Question on Stackoverflow, [link here](https://stackoverflow.com/questions/45654097/mysql-replication-to-create-stream-does-not-restart-reading-binlog-records-from):

I'm trying to use withBinLogPosition(..) when constructing the MYSQLReplicationFactory, as follows:

             $dbStream = new MySQLReplicationFactory(
                (new ConfigBuilder())
                    ->withUser($userName)
                    ->withPassword($password)
                    ->withHost($hostName)
                    ->withEventsOnly([
                        ConstEventType::UPDATE_ROWS_EVENT_V1, ConstEventType::UPDATE_ROWS_EVENT_V2,
                        ConstEventType::WRITE_ROWS_EVENT_V1, ConstEventType::WRITE_ROWS_EVENT_V2,
                        ConstEventType::DELETE_ROWS_EVENT_V1, ConstEventType::DELETE_ROWS_EVENT_V2,
                    ])
                    ->withSlaveId(9999)
                    ->withBinLogPosition($binLogPosition)
                    ->build()
            );
            // register benchmark subscriber handler
            $dbStream->registerSubscriber(new MysqlStreamEventSubscribers($logger));

In above piece of code, I've not specified withBinLogFileName(..). I assume specifying log file name to start with is not needed (correct if wrong?). When the value of $binLogPosition is something which has already been received, the above code does not replay from that log position onwards. I don't get any old records, just get any newer DB events. Any pointer to where I'm going wrong would be helpful.

**Comment by pushkarprasad007** [comment]
Okay, I figured that providing the bin Log File Name is also needed, so I did that

                ->withBinLogFileName('binlog.000003')
                ->withBinLogPosition($binLogPosition)
                ->build()

However, I'm getting this:

An exception occurred while executing '\n             SELECT\n                `COLUMN_NAME`,\n                `COLLATION_NAME`,\n                `CHARACTER_SET_NAME`,\n                `COLUMN_COMMENT`,\n                `COLUMN_TYPE`,\n                `COLUMN_KEY`\n            FROM\n                `information_schema`.`COLUMNS`\n            WHERE\n                    `TABLE_SCHEMA` = ?\n                AND\n                    `TABLE_NAME` = ?\n       ' with params [\"zestlZviceLibraryPune\", \"UserCartItems\"]:\n\nSQLSTATE[HY000]: General error: 2006 MySQL server has gone away

But when I'm removing both the withBinLogPosition and withBinLogFile, the thing was working perfectly fine, now has started to give errors:

PHP Notice:  Undefined index: COLUMN_NAME in /var/www/html/vendor/krowinski/php-mysql-replication/src/MySQLReplication/Event/RowEvent/Columns.php on line 30
PHP Notice:  Undefined index: CHARACTER_SET_NAME in /var/www/html/vendor/krowinski/php-mysql-replication/src/MySQLReplication/Event/RowEvent/Columns.php on line 32
.. And so on

**Comment by pushkarprasad007** [comment]
Just to give you another sample data, I was able to run the noplay python library properly, it works like a charm, with the same arguments for bin Log File and bin Log Position.

**Comment by krowinski** [comment]
Hi what mysql  version/os are u using ? you got this error right away or after some time ?

**Comment by pushkarprasad007** [comment]
I'm using MYSQL 5.6, and its running on AWS RDS. 

Another Issue I notice is :
I keep getting once in a while the following too (The DB Schema has not changed for sure, why do I keep getting Dropped Columns?):

\n=== Event write === \nDate: 2017-08-15T14:27:15+00:00\nLog position: 4621\nEvent size: 148\nTable: custom_form_submissions_metadata\nAffected columns: 25\nChanged rows: 1\nValues: Array\n(\n    [0] => Array\n        (\n            [FormSubmissionID] => 4949\n            [FormID] => 1675\n            [FormTitle] => 455\n            [ZviceID] => 995\n            [ZbotID] => Amount\n            [ModifiedBy] => Amount\n            [DateModified] => timestamp\n            [CreatedBy] => \n            [DateCreated] => \n            [IsHistory] => 1\n            [ParentFormSubmissionID] => 4\n            [OnBehalfOfZviceID] => \n            [Flags] => \n            [Deleted] => tinyint(1\n            [DROPPED_COLUMN_14] => \n            [DROPPED_COLUMN_15] => \n            [DROPPED_COLUMN_16] => \n            [DROPPED_COLUMN_17] => \n            [DROPPED_COLUMN_18] => \n            [DROPPED_COLUMN_19] => \n            [DROPPED_COLUMN_20] => \n            [DROPPED_COLUMN_21] => \n            [DROPPED_COLUMN_22] => \n            [DROPPED_COLUMN_23] => \n            [DROPPED_COLUMN_24] => \n        )\n\n)\n\n","data":null}

**Comment by pushkarprasad007** [comment]
Just FYI, if I use python noplay library, the thing works perfectly fine.

**Comment by krowinski** [comment]
If you have time try version 3.0.1 probably not cleaning cache after rotate event was the cause here

**Comment by pushkarprasad007** [comment]
No luck. Again, just to reiterate, the thing works perfectly on noplay. If you want, I can give you the credentials and the hostname, password etc of the RDS server. Its for testing only, so I'm fine with that.

PHP Notice:  Undefined index: COLUMN_NAME in /var/www/html/vendor/krowinski/php-mysql-replication/src/MySQLReplication/Event/RowEvent/Columns.php on line 30
PHP Stack trace:
PHP   1. {main}() /opt/mysqlstream/MysqlStreamDaemon.php:0
PHP   2. MysqlStreamDaemon->run() /opt/mysqlstream/MysqlStreamDaemon.php:226
PHP   3. MysqlStreamDaemon->consume() /opt/mysqlstream/MysqlStreamDaemon.php:185
PHP   4. MySQLReplication\MySQLReplicationFactory->consume() /opt/mysqlstream/MysqlStreamDaemon.php:204
PHP   5. MySQLReplication\Event\Event->consume() /var/www/html/vendor/krowinski/php-mysql-replication/src/MySQLReplication/MySQLReplicationFactory.php:124
PHP   6. MySQLReplication\Event\RowEvent\RowEvent->makeTableMapDTO() /var/www/html/vendor/krowinski/php-mysql-replication/src/MySQLReplication/Event/Event.php:100
PHP   7. MySQLReplication\Event\RowEvent\Columns::parse() /var/www/html/vendor/krowinski/php-mysql-replication/src/MySQLReplication/Event/RowEvent/RowEvent.php:152
PHP Notice:  Undefined index: COLLATION_NAME in /var/www/html/vendor/krowinski/php-mysql-replication/src/MySQLReplication/Event/RowEvent/Columns.php on line 31
PHP Stack trace:

**Comment by krowinski** [comment]
If its not a problem sure send me credentials to my email kacper.rowinski@gmail.com 
It could be problem with dbal/mysql configuation or something else..

**Comment by pushkarprasad007** [comment]
Sent Kacper, please check

**Comment by pushkarprasad007** [comment]
Its still not happening, and may be its because the thing is running on EC2 Amazon linux? I can share credentials for that one too if you are interested.

**Comment by krowinski** [comment]
Ok we found problem with forking consumers, sql for columns schema returns [0] => [0 => 1] probably dbal is losing connection (?) For now best is not to use forking.

**Comment by pushkarprasad007** [comment]
Thanks. Will work around that. It is not a big restriction anyway

On Aug 24, 2017 2:22 PM, "Kacper Rowiński" <notifications@github.com> wrote:

Ok we found problem with forking consumers, sql for columns schema returns
[0] => [0 => 1] probably dbal is losing connection (?) For now best is not
to use forking.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/krowinski/php-mysql-replication/issues/26#issuecomment-324575029>,
or mute the thread

**Comment by krowinski** [comment]
dbal is not reconnecting when forked is created, its php internal problem (more to similar case in https://php.net/manual/en/function.pcntl-fork.php#70721)
