### ISSUE TITLE
[ErrorException]    unpack(): Type i:

### ISSUE THREAD

**Issue by leoliuxd** [krowinski/php-mysql-replication#28]
I came across a fetal error:

[ErrorException]                                    
  unpack(): Type i: not enough input, need 4, have 2

only in src/MySQLReplication/BinLog/BinLogServerInfo.php there are same function call,
       
 self::$serverInfo['connection_id'] = unpack('I', $data[$i] . $data[++$i] . $data[++$i] . $data[++$i])[1];

**Comment by krowinski** [comment]
Hi, what version of mysql are u using ? ```select version()```

**Comment by leoliuxd** [comment]
5.6.16-log

**Comment by leoliuxd** [comment]
my client is Mac OS x10.12.5 ,  PHP 7.0.14

**Comment by leoliuxd** [comment]
i just  downgrade php  toPHP 5.6.30  and 
  [ErrorException]                                    
  unpack(): Type I: not enough input, need 4, have 0

**Comment by krowinski** [comment]
Tested  php example/dump_events.php on  OSX 10.12.6 mysql installed from homebrew 5.6.37-log
no problems there. Did you add https://github.com/krowinski/php-mysql-replication#mysql-server-settings to my.cnf ? Show me you code do u use files from example ?

**Comment by leoliuxd** [comment]
Maybe i have found what's the problem, it seems that the  mysql character_set affects the parse of binlog. The decoder should be the same with mysql character_set. Thanks ^^

**Comment by krowinski** [comment]
what charset u use in binlog ?

**Comment by leoliuxd** [comment]
I set  that to gbk, but the problem still exist. Some column is set BLOB type.
