### ISSUE TITLE
saving binlog filename

### ISSUE THREAD

**Issue by rbro** [krowinski/php-mysql-replication#33]
I'm trying to figure out how to save the current binlog filename when a script exits, so it can restart where it left off using the filename and position.

I see the binlog position comes in every event, and there is a Rotate event where you get the new binlog filename when the filename changes, but what if Rotate is never called and your script exits?  Is there a way to pull the current binlog filename on connect or in every event?

Thanks for your help.

**Comment by krowinski** [comment]
Hi! 
Right now its not added to event, only set in config or if no bin pos was given taken form sql = master status. 
(https://github.com/krowinski/php-mysql-replication/blob/a6a24c50f030c854f8b644787cd6dae5a381f72f/src/MySQLReplication/BinLog/BinLogSocketConnect.php#L242)

You can assume that config bin pos is a "current" and use it until rotate event appear. 

In future I will add "current" binlog possition and file to EventDTO and write some example how to return.

**Comment by rbro** [comment]
Thanks.  Yes, I think adding it to the Event would help as right now, if you don't set the binlog filename in the config, you don't have a way to know what it is once it starts reading the binary log.  I see that the setBinLogDump function calls getMasterStatus(), which returns the current binlog filename, but there's no way to access it as it's not saved into any class property for later access.

**Comment by krowinski** [comment]
@rbro checkout pull #34 I still need to test mariadb gtid and gtid but binlog pos sould work fine from my tests

**Comment by rbro** [comment]
@krowinski Thanks so much for the quick update and examples.  That works great.  I like how the Rotate event is now handled automatically, so you don't have to write a custom handler for it.

**Comment by krowinski** [comment]
merged to master and tag created as 4.0 HF
