### ISSUE TITLE
MySQLReplicationFactory constructor - no arguments

### ISSUE THREAD

**Issue by rbro** [krowinski/php-mysql-replication#35]
I'm not sure if this is intended, but I noticed that the examples are passing a Config object when creating a MySQLReplicationFactory object, but it doesn't look like the constructor for MySQLReplicationFactory is using it, as the constructor doesn't have any arguments.  It looks like the constructor is always referencing a static instance of the Config object, which seems to be the last Config object created.

**Comment by krowinski** [comment]
Yes I forgot to change examples this when I was done with refactoring
