### ISSUE TITLE
Trancate Bug

### ISSUE THREAD

**Issue by dulumao** [krowinski/php-mysql-replication#37]
If use the truncate, the event will not be recorded.

**Comment by krowinski** [comment]
Tested on percona 5.6.39 and recived event

```

=== Event query ===
Date: 2018-05-15T06:38:34+00:00
Log position: 327
Event size: 88
Database: test1
Execution time: 0
Query: TRUNCATE TABLE `fff`
Memory usage 2.08 MB

```

**Comment by krowinski** [comment]
@dulumao I added integration tests for that (so event is generated in mysql 5.6, 5.7 and mariadb 10.3). Can you send me how your php configuration or example how you test it ? 

You shoud recive truncate in QueryEvent (more in https://github.com/krowinski/php-mysql-replication/blob/master/tests/Integration/BasicTest.php#L246)

**Comment by dulumao** [comment]
@krowinski I re-tested and found normal.
