### ISSUE TITLE
Event Query:COMMIT and Event xid

### ISSUE THREAD

**Issue by liujian883** [krowinski/php-mysql-replication#4]
Hi,
I tested the code on my ubuntu 14.04,and I sometimes got the 
Event Query: COMMIT ,sometimes got Event xid;
would you mind explain the difference between the two events;
are they meaning of the end of a Transaction( for example : SQL statement: begin; insert .. update..or some other SQLs ; commit;)???
THANKS!!!

**Comment by krowinski** [comment]
Hi, 

> QUERY_EVENT
> 
> Written when an updating statement is done.


> XID_EVENT
> 
> Generated for a commit of a transaction that modifies one or more tables of an XA-capable storage engine. Normal transactions are implemented by sending a QUERY_EVENT containing a BEGIN statement and a QUERY_EVENT containing a COMMIT statement (or a ROLLBACK statement if the transaction is rolled back).
> 

So its depends on what storage engine you use. In most cases you can use QUERY_EVENT

 https://dev.mysql.com/doc/internals/en/event-meanings.html
