### ISSUE TITLE
Cannot make a connection to a remote mysql server

### ISSUE THREAD

**Issue by jimmytuc** [krowinski/php-mysql-replication#40]
* *Operating System*: OS X
* *PHP Version*: 7.1
* *php-mysql-replication Version*: latest

1. Remote server configuration:
```
$binLogStream = new MySQLReplicationFactory(
    (new ConfigBuilder())
        ->withUser('remote_user')
        ->withHost('101.1**.2**.1**')
        ->withPassword('password')
        ->withDatabasesOnly([
                'db_1'
        ])
        ->withTablesOnly([
                'tb_1'
        ])
        ->build()
);
```

> Expected Result.

* Event stream listening like example tested

> Actual Result.
Please see the image below
<img width="610" alt="reproduce" src="https://user-images.githubusercontent.com/3124405/41084216-ad81129e-6a5d-11e8-9655-d6e6a225d36b.png">

**Comment by krowinski** [comment]
Hi @jimmytuc I think you have problem with user host permissions 

Can you run
``` select host  from mysql.user where user = 'remote_user'```

and check if ip that you connecting from is the same as in mysql.user

More info https://dev.mysql.com/doc/refman/5.7/en/create-user.html
