### ISSUE TITLE
How to fix exception about unknown row type 11

### ISSUE THREAD

**Issue by huangdijia** [krowinski/php-mysql-replication#41]
> Please provide the following details.

* *Operating System*: Linux
* *PHP Version*: 7.1
* *php-mysql-replication Version*: 5.0.1

> Unknown row type: 11

**Comment by krowinski** [comment]
Is that row 11 is a TIME column that is not supported, can you give me your create table with this column ? I will try to recreate this and add this column type.

**Comment by huangdijia** [comment]
MySQL version: `5.5.11-log - Source distribution`

create table sql like this:
```
CREATE TABLE `t8_online_service_user_record` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `login_date` date NOT NULL DEFAULT '0000-00-00',
  `admin_uid` int(11) NOT NULL DEFAULT '0',
  `service_id` int(11) NOT NULL DEFAULT '0',
  `first_beat` time NOT NULL DEFAULT '00:00:00',
  `last_beat` time NOT NULL DEFAULT '00:00:00',
  PRIMARY KEY (`id`),
  UNIQUE KEY `ldausi` (`login_date`,`admin_uid`,`service_id`),
  KEY `ldau` (`login_date`,`admin_uid`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=latin1;
```

**Comment by krowinski** [comment]
Ok you have mysql 5.5 and its not fully supported but I added TIME = 11 in new branch so it should be soon in master.

**Comment by huangdijia** [comment]
@krowinski Thanks
