### ISSUE TITLE
EOF packet not handled

### ISSUE THREAD

**Issue by tzunghaor** [krowinski/php-mysql-replication#42]
* *Operating System*: Linux 
* *PHP Version*:  7.1 
* *php-mysql-replication Version*: 5.0.1

> Steps required to reproduce the problem.

1. Start example/dump_events
2. Restart replication server

> Expected Result.

* dump_events exits simply with "Disconnected by remote side" or similar exception

> Actual Result.

* Before "Disconnected by remote side" exception, there are a few "Warning:  unpack(): Type C: not enough input, need 1, have 0" errors

> Cause

On restart the replication server sends an [EOF packet](https://dev.mysql.com/doc/internals/en/packet-EOF_Packet.html) is sent. The Event::consume() method simply skips the first byte, assuming it is an OK byte and tries to unpack a full OK header - this fails, since the EOF packet is much shorter.

---

First of all, thanks for this library.

The issue is not that severe, since the script exits anyhow, but since the unpack errors came first in our logs, we thought that the replication server sent an illegal packet, and spent a few hours investigating in that direction.

**Comment by krowinski** [comment]
Hi tx for feedback, fix should be in new branch soon should be added to master

**Comment by tzunghaor** [comment]
Thank you, that was quick.
