### ISSUE TITLE
Notice: Undefined offset: -1

### ISSUE THREAD

**Issue by jury89** [krowinski/php-mysql-replication#5]
Hi

I am having this error:
`Symfony\Component\Debug\Exception\ContextErrorException: Notice: Undefined offset: -1 (uncaught exception) at /var/www/html/salesforce-bridge/shared/vendor/krowinski/php-mysql-replication/src/MySQLReplication/Event/RowEvent/RowEvent.php line 372 while running console command `my:task` {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Notice: Undefined offset: -1 at /var/www/html/salesforce-bridge/shared/vendor/krowinski/php-mysql-replication/src/MySQLReplication/Event/RowEvent/RowEvent.php:372)"}`

Do you know why is this error raised? It looks like it's related with the ENUM fields, which I am using in my table, but apparently i don't get the error always but just some times.

Thanks,
Jury

**Comment by krowinski** [comment]
Hi,

Can you send me a create table sql with column and its enum ? 

I will try to replicate this issue.

**Comment by jury89** [comment]
Here is the query [Users.sql.zip](https://github.com/krowinski/php-mysql-replication/files/250712/Users.sql.zip)

Thanks,
Jury

**Comment by krowinski** [comment]
Ok I found why its happening its because there is an update/insert with value that don't exists in enum. 
And when I try to map this value to exsiting enums I can't find it and replicator generate this error.

I will fix this today.

**Comment by jury89** [comment]
Oh great, thank you for your help @krowinski!

**Comment by krowinski** [comment]
New tag 1.0.2 released with fix for this issue :)
