### ISSUE TITLE
getDatetime2 not reads fsp when date is wrong

### ISSUE THREAD

**Issue by Stern87** [krowinski/php-mysql-replication#54]
> Please provide the following details.

* *Operating System*: Linux
* *PHP Version*: 7.1
* *php-mysql-replication Version*: 5.0.5
* *mysql version (```SELECT VERSION();```):  5.7.26-log

> Steps required to reproduce the problem.

1. Have a table with column type DATETIME(6) NOT NULL - with fractional seconds
2. Update any row and set value of this column to NULL
3. Now you will receive an event that will fail when try to read value of any fields that go after mentioned above

> Expected Result.

* All data from binaryDataReader should go well after reading value from column with DATETIME(6) NOT NULL type

> Actual Result.

* binaryDataReader can't read next data because in the getDatetime2 function return null goes before it runs getFSP

**Comment by Stern87** [comment]
#55

**Comment by Stern87** [comment]
Thanks for approving pull request and merging to master branch!
When the new version will be released?

**Comment by Stern87** [comment]
Many thanks!

**Comment by krowinski** [comment]
Tx for fix

I just released new tag,
