### ISSUE TITLE
Large array is parsed as an object

### ISSUE THREAD

**Issue by rusuly** [krowinski/php-mysql-replication#59]
https://github.com/krowinski/php-mysql-replication/blob/064a98712bcd10c2ab7e226d652e45f898be42c4/src/MySQLReplication/JsonBinaryDecoder/JsonBinaryDecoderService.php#L74

Hi, again.
I think I spotted a bug when looking at the class.
Since [mysql-binlog-connector-java](https://github.com/shyiko/mysql-binlog-connector-java/pull/288) hasn't been supported for a while I was looking for how different libraries handle empty holes made by partial updates in JSON(some complain it occurs in MySQL 8.0.16+).

**Comment by krowinski** [comment]
Hi, good catch its should be array. Funny thing is that in php you can decide when unserialising json is array|object so event if I decode as object still you can do json_encode($json, true) and get array... 
 
Fix and test should be soon tx!

**Comment by rusuly** [comment]
Also, be informed that in-place updates make empty holes between keys and values as described in the [spec](https://dev.mysql.com/worklog/task/?id=8132#tabs-8132-4)

Steps to reproduce (redproduced from MySQL 8.0.16+):
`
UPDATE t1 SET JsonColumn='{"id": 1, "name": "Monica", "types":[1,"123"]}' WHERE Id = 1;
UPDATE t1 SET JsonColumn = JSON_SET(JsonColumn, '$.name', 'Mon') WHERE id = 1;
`
This will create 3-byte hole in the "name" value so you need to advance the stream.

**Comment by krowinski** [comment]
hmm even is you do

```
UPDATE t1 SET j='{"id": 1, "name": "Monica", "types":"test"}' WHERE id = 1
UPDATE t1 SET j = JSON_SET(j, '$.name', 'Mon') WHERE id = 1
```

it will work but you get strange json 
```
"{"id":1,"name":"Mon","types":"catest"}"
```

its take from Monica - ca and add to types 🙄

**Comment by krowinski** [comment]
I don't see any other way to skip unused offset like it was done here

https://github.com/johnyang007/mysql-binlog-connector-java/commit/2fdea43c68d24c4e4defdb7b92ced7a255c1eca9

futhermore I don't see any solution even in mysql-server code 

https://github.com/mysql/mysql-server/blob/8.0/sql/json_binary.cc

```  Since we're replacing one string with a shorter one, we can just overwrite
  the length byte with the new length, and the beginning of the original string
  data. Since the original string "abc" is longer than the new string "XY",
  we'll have a free byte at the end of the string. This byte is left as is
  ('c'). ```

Its should work as we read binary data and still it's not cutting correctly.

**Comment by rusuly** [comment]
Hi, 

In my lib I calculate unused space and skip it using [Advance](https://github.com/rusuly/MySqlCdc/blob/19b40e504c75c0d5ec1c07ceed459bfe3b1512e1/src/MySqlCdc/Providers/MySql/Json/JsonParser.cs#L174) method

I think we don't see it in mysql-server code because it is written in C and it accesses memory directly using offsets(it doesn't read the stream in cursor-like style like our libraries do).

**Comment by krowinski** [comment]
Ok its fixed now, added new test based on yangkun code to verified this and looks good. Also I redone all code based on mysql server code.
