### ISSUE TITLE
Symfony 5.0 support?

### ISSUE THREAD

**Issue by m-h-1** [krowinski/php-mysql-replication#60]
do you plan to support Symfony 5?
`
"require": {
    "php": ">=7.1",
    "ext-sockets": "*",
    "ext-json": "*",
    "ext-bcmath": "*",
    "doctrine/dbal": "^2.5",
    "doctrine/collections": "^1.3",
    "symfony/event-dispatcher": "^2.8|^3.1|^4.0",
    "symfony/dependency-injection": "^2.8|^3.1|^4.0",
    "psr/simple-cache": "^1.0"
  },
`

**Comment by krowinski** [comment]
yes I plan

**Comment by m-h-1** [comment]
nice 👌, is there a timeframe or can i support you?

**Comment by krowinski** [comment]
this week, sure you can fork and test if adding |^5.0 to composer json will pass all test

**Comment by m-h-1** [comment]
thanks

**Comment by m-h-1** [comment]
#61

**Comment by krowinski** [comment]
tag released tx!
