### ISSUE TITLE
Exception: Could not find first log file name in binary log index file (bad filename)

### ISSUE THREAD

**Issue by jnunez166** [krowinski/php-mysql-replication#62]
> Please provide the following details.

* *Operating System*: Linux
* *PHP Version*: 7.1
* *php-mysql-replication Version*: v6.2.0
* *mysql version (```SELECT VERSION();```):  10.3.21-MariaDB-1:10.3.21+maria~stretch-log

> Steps required to reproduce the problem.

1. Start a listener
2. Trigger events
3. CTRL-C to quit the listener
4. Start the listener again

> Expected Result.

* Continue listening from last position

> Actual Result.

* Exception: Could not find first log file name in binary log index file. The filename always contains non-printable characters at the end "mysql-bin.007566ݬp". Does not always happen. But 3 out of 5 attempts will cause this issue.

**Comment by krowinski** [comment]
tx for reporting this, mariadb < 10 have  different header size then mariadb 5.5 

fixed in 6.2.1
