### ISSUE TITLE
bug in update

### ISSUE THREAD

**Issue by questionlin** [krowinski/php-mysql-replication#63]
> Please provide the following details.

* *Operating System*: <OS X>
* *PHP Version*: <7.3.9>
* *php-mysql-replication Version*: <6.2>
* *mysql version (```SELECT VERSION();```):  <5.7.21-log >

> Steps required to reproduce the problem.

1. 
```
CREATE TABLE `cache` (
  `key` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `value` varchar(16100) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'memory引擎不支持text',
  `expiration` int(11) NOT NULL,
  UNIQUE KEY `cache_key_unique` (`key`)
) ENGINE=MEMORY DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
```
2. 
insert `cache` values ('laravel_cache5c785c036466adea360111aa28563bfd556b5fba','i:1','-1942153413')
3. 
update `cache` set `key`='laravel_cache5c785c036466adea360111aa28563bfd556b5fba', `value`='i:2', expiration='1586248983'
> Expected Result.

Date: 2020-04-07T16:42:03+08:00
Log position: 67042
Event size: 168
Table: cache
Affected columns: 3
Changed rows: 1
Values: Array
(
    [0] => Array
        (
            [before] => Array
                (
                    [key] => laravel_cache5c785c036466adea360111aa28563bfd556b5fba
                    [value] => i:1
                    [expiration] => -1942153413
                )

            [after] => Array
                (
                    [key] => laravel_cache5c785c036466adea360111aa28563bfd556b5fba
                    [value] => i:2
                    [expiration] => 1586248983
                )

        )

)

> Actual Result.

Date: 2020-04-07T16:42:03+08:00
Log position: 67042
Event size: 168
Table: cache
Affected columns: 3
Changed rows: 1
Values: Array
(
    [0] => Array
        (
            [before] => Array
                (
                    [key] => laravel_cache5c785c036466adea360111aa28563bfd556b5fba
                    [value] => i:1
                    [expiration] => -1942153413
                )

            [after] => Array
                (
                    [key] => laravel_cache5c785c036466adea360111aa28563bfd556b5fbai:2;=?^?%9
                    [value] => 
                    [expiration] => 
                )

        )

)

**Comment by questionlin** [comment]
besides it also has many other problems like 
Values: Array
(
    [0] => Array
        (
            [key] => laravel_cache5c785c036466adea360111aa28563bfd556b5fba:timer
            [value] => i:1586248983
            [expiration] => -1942153413
        )

    [1] => Array
        (
            [key] => ?*
            [value] => 
            [expiration] => 
        )

)

Values: Array
(
    [0] => Array
        (
            [key] => laravel_cache5c785c036466adea360111aa28563bfd556b5fba
            [value] => i:8
            [expiration] => -1942333893
        )

    [1] => Array
        (
            [key] => $
            [value] => 
            [expiration] => 
        )

)

**Comment by krowinski** [comment]
I found problem with " varchar(16100)" I was reading it as signed int and it should be read as unsigned. Fix in master.
