### ISSUE TITLE
can you update your composer library doctrine/dbal from2.5 to 2.9

### ISSUE THREAD

**Issue by linlancer** [krowinski/php-mysql-replication#65]
there are many bugs find in doctrine/dbal on 2.5 such as vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php in line 273  there is a obvious  spelling mistake;
the word Fboreign should be Foreign , we used the method so cause the fatal error;

**Comment by krowinski** [comment]
Composer json have "doctrine/dbal": "^2.5", so if there is 2.9 version it will be automatically downloaded or updated (composer update) 

- Installing doctrine/dbal (v2.9.3):
