### ISSUE TITLE
Events not triggered with PRIMARY (statement) -> REPLICA (row) -> php-mysql-replication

### ISSUE THREAD

**Issue by bpolaszek** [krowinski/php-mysql-replication#71]
* *Operating System*: Debian
* *PHP Version*: 7.4
* *php-mysql-replication Version*: 6.2.4

Hello there,

We've got a running architecture of 1 primary (let's call it `Bob`) replicating to 10 replicas (new wording for master / slaves).
I'd like to watch for insert / update events with your package, but `Bob` currently replicates through the `STATEMENT`  binlog format.

Since _php-mysql-replication_ cannot work with this binlog format for insert / update events, I assumed that I could create an 11th replica just for this purpose (let's call it `Alice`), with its own binlog format set to `ROW`.

Problem is, when plugging _php-mysql-replication_ on `Alice`:
- If I perform insert / updates on `Alice` directly, insert / updates are triggered and catchable in PHP ✅
- However, when performing insert / updates on `Bob`, nothing is triggered (tho data is properly replicated on `Alice`). 🚫

Assuming that binlog format cannot be changed on `Bob` (it's prod, running thousands of queries/s, replicating to datacenters locatedx on other continents) since it involves a high regression risk, do you know if I have a mean to solve this? Maybe I just missed some MySQL configuration?

FYI I performed my tests on dev servers, where `Bob` is a MariaDB 10.1. 
On production, `Bob` is a MySQL 5.5 (I know... but I doubt that changes anything to the issue).
Prod and dev run on Debian. `Alice` runs MySQL 5.7 on Ubuntu.

Thank you,
Ben

**Comment by bpolaszek** [comment]
Found out the solution.

For the records, this has to be set on `Alice` to work:

```
[mysqld]
log_slave_updates = on
```

**Comment by krowinski** [comment]
yes indeed this will work tx for sharing
