### ISSUE TITLE
Cannot see rows affected through triggers

### ISSUE THREAD

**Issue by jasimaz** [krowinski/php-mysql-replication#77]
> Please provide the following details.

* *Operating System*: Ubuntu 18.04
* *PHP Version*: 7.2.24
* *php-mysql-replication Version*: 6.2.4
* *mysql version (```SELECT VERSION();```):  MySQL 8

> Steps required to reproduce the problem.

Happening all the time

> Expected Result.

Tried using row, statement, mixed based events but cannot see rows inserted, updated, deleted by triggers

> Actual Result.

No Events

**Comment by krowinski** [comment]
hmm I created simple trigger 
```
CREATE TRIGGER `test` BEFORE UPDATE ON `foo`
 FOR EACH ROW update bar  set bar.updated_at = now()
 ```
and I received events.

Are you sure you have ```binlog-format    = row```  in your conf ?

**Comment by jasimaz** [comment]
Sorry Krowinski looks it the issue was on the RDS. Its resolved now and I am getting events generated from triggers on row based application.

**Comment by krowinski** [comment]
cool 👍
