### ISSUE TITLE
Event id is always same

### ISSUE THREAD

**Issue by jasimaz** [krowinski/php-mysql-replication#83]
> Please provide the following details.

* *Operating System*: Ubuntu 18.04
* *PHP Version*: 7.2.4
* *php-mysql-replication Version*: 7.0
* *mysql version (```SELECT VERSION();```):  8

> Steps required to reproduce the problem.

Read all the events

> Expected Result.

Each event should have a unique id

> Actual Result.

* 
![image](https://user-images.githubusercontent.com/25701241/114626263-81321c00-9cc4-11eb-9670-b9159886805a.png)

**Comment by krowinski** [comment]
ok its misleading name is a "server Id" not an event "id"

**Comment by jasimaz** [comment]
HI @krowinski ,

Thank you for the response. Can you also tell me if there is a way to get unique id for each message. It is possible or anyway available ?


Regards,

**Comment by krowinski** [comment]
there is no id that mysql generate for event you can try to create hash using binary file + binarny position

**Comment by krowinski** [comment]
changed to server  id in #104
