### ISSUE TITLE
PHP 8.1: spammed with warnings

### ISSUE THREAD

**Issue by quakemmo** [krowinski/php-mysql-replication#89]
Great job, this is a very useful piece of code.
Small issue here with PHP 8.1:

* *Operating System*: <Linux | Windows | OS X>
```Linux```

* *PHP Version*: <5.6 | 7.0 | ...>
```PHP 8.1```

* *php-mysql-replication Version*: <1.0.0>
```1.0.0```

* *mysql version
```Oracle-MYSQL 8.0.27 ```

> Steps required to reproduce the problem.
```
1. Run the dump_events.php
2. Get spammed by deprecated warnings
```
> Expected Result.
```Not get spammed by warnings``` 

> Actual Result.

```
Return type of MySQLReplication\Event\EventInfo::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /<path>/vendor/krowinski/php-mysql-replication/src/MySQLReplication/Event/EventInfo.php on line 100

```

**Comment by Moln** [comment]
You can try this fork https://github.com/Moln/php-mysql-replication .

Resolve these issues:

- Add regular expression matching support for DatabasesOnly or TablesOnly of Config.
- Resolve krowinski/php-mysql-replication#94, change static config properties to non-static.
- Add retry feature.
   ```php
   (new ConfigBuilder())
     ->withRetry(-1) // Retry always.
     ->withRetry(0)  // Disable retry feature. (Default)
     ->withRetry(2)  // Retry twice.
   ```
- PHP 8.1,8.2 supports.

**Comment by krowinski** [comment]
8.1 no more supported move to 8.2 with version #104
