### ISSUE TITLE
Let's `Config` static properties to non-static.

### ISSUE THREAD

**Issue by Moln** [krowinski/php-mysql-replication#94]
I will try use it combine swoole for connect multiple replications. Let's `Config` static properties to non-static will be better. 

```php
$config = (new ConfigBuilder())
    ->withUser('root')
    ->withHost('192.168.1.10')
    ->withPort(3306)
    ->withPassword('123456')
    ->build();

$config2 = (new ConfigBuilder())
    ->withUser('root')
    ->withHost('192.168.1.11')
    ->withPort(3306)
    ->withPassword('123456')
    ->build();

var_dump($config->getHost()); //192.168.1.11
```

> Expected Result.

Output: `192.168.1.10`

> Actual Result.

Output: `192.168.1.11`

**Comment by krowinski** [comment]
Hi, I can change this but I think you will unable to run consume in one php process.

**Comment by krowinski** [comment]
done in #104
