### ISSUE TITLE
Slave_UUID field displays abnormal

### ISSUE THREAD

**Issue by bb7788** [krowinski/php-mysql-replication#99]
> Please provide the following details.

* *Operating System*: OS X
* *PHP Version*:  PHP 7.3.29
* *php-mysql-replication Version*: 7.0.1
* *mysql version (```SELECT VERSION();```):  5.7.32-log

> Steps required to reproduce the problem.

1. Run the resuming.php
2. Run “SHOW SLAVE HOSTS;” on MySQL

> Expected Result.

Slave_UUID field displays abnormal

<failed to load>
java.lang.ArrayIndexOutOfBoundsException: Index 34 out of bounds for length 34
	at org.mariadb.jdbc.internal.com.read.resultset.rowprotocol.TextRowProtocol.setPosition(TextRowProtocol.java:135)
	at org.mariadb.jdbc.internal.com.read.resultset.SelectResultSet.checkObjectRange(SelectResultSet.java:639)
	at org.mariadb.jdbc.internal.com.read.resultset.SelectResultSet.getString(SelectResultSet.java:947)
	in JdbcHelperImpl.getObject(JdbcHelperImpl.java:303)

<img width="1302" alt="image" src="https://github.com/krowinski/php-mysql-replication/assets/14172278/cc0fa0e5-b0ee-4cd1-b4a9-77a3ae1a84f9">

> Actual Result.

*

**Comment by krowinski** [comment]
Hi, replicator don't set Slave_UUID so its empty string and java tries to set as uuid obj ? 

I add this to my todo list

**Comment by krowinski** [comment]
Added withSlaveUuid  with default uuid = 0015d2b6-8a06-4e5e-8c07-206ef3fbd274
